# Generated by Django 5.2.5 on 2026-01-07 07:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0007_applicationmodel_current_stage_and_more'),
        ('job', '0006_rename_screenig_started_at_jobmodel_screening_started_at'),
        ('selection_process', '0004_alter_selectionprocessmodel_job_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelephonicInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_duration_minutes', models.IntegerField(default=30)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=100)),
                ('status', models.CharField(choices=[('not_scheduled', 'Not Scheduled'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('failed', 'Failed')], db_index=True, default='not_scheduled', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('actual_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('interviewer_notes', models.TextField(blank=True, null=True)),
                ('scheduling_notes', models.TextField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telephonic_interview', to='application.applicationmodel')),
                ('conducted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_interviews', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telephonic_interviews', to='job.jobmodel')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telephonic_interviews', to='selection_process.selectionstagemodel')),
            ],
            options={
                'db_table': 'telephonic_interviews',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewTranscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_text', models.TextField()),
                ('segments', models.JSONField(default=list)),
                ('detected_language', models.CharField(default='en', max_length=10)),
                ('confidence', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('model_used', models.CharField(default='whisper-1', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcription', to='telephonic_round.telephonicinterview')),
            ],
            options={
                'db_table': 'interview_transcriptions',
            },
        ),
        migrations.CreateModel(
            name='InterviewPerformanceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('communication_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('technical_knowledge_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('problem_solving_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('enthusiasm_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('clarity_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('professionalism_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('decision', models.CharField(choices=[('qualified', 'Qualified'), ('not_qualified', 'Not Qualified'), ('pending', 'Pending Review')], default='pending', max_length=20)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('key_highlights', models.JSONField(default=list)),
                ('areas_for_improvement', models.JSONField(default=list)),
                ('technical_assessment', models.TextField(blank=True, null=True)),
                ('communication_assessment', models.TextField(blank=True, null=True)),
                ('key_topics_discussed', models.JSONField(default=list)),
                ('questions_asked_count', models.IntegerField(default=0)),
                ('candidate_response_quality', models.CharField(blank=True, max_length=20, null=True)),
                ('manual_score_override', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('manual_decision_override', models.CharField(blank=True, choices=[('qualified', 'Qualified'), ('not_qualified', 'Not Qualified')], max_length=20, null=True)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('ai_model_used', models.CharField(default='gemini-pro', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_interviews', to=settings.AUTH_USER_MODEL)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_result', to='telephonic_round.telephonicinterview')),
            ],
            options={
                'db_table': 'interview_performance_results',
            },
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('strengths', models.TextField()),
                ('weaknesses', models.TextField()),
                ('recommendation', models.CharField(choices=[('strong_yes', 'Strong Yes'), ('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No'), ('strong_no', 'Strong No')], max_length=20)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provided_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_feedback', to='telephonic_round.telephonicinterview')),
            ],
            options={
                'db_table': 'interview_feedbacks',
            },
        ),
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('peer_connection_id', models.CharField(blank=True, max_length=100, null=True)),
                ('caller_id', models.CharField(max_length=100)),
                ('callee_id', models.CharField(max_length=100)),
                ('connection_quality', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('is_recording', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('recording_key', models.CharField(blank=True, max_length=500, null=True)),
                ('recording_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('recording_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_session', to='telephonic_round.telephonicinterview')),
            ],
            options={
                'db_table': 'call_sessions',
            },
        ),
        migrations.CreateModel(
            name='TelephonicRoundSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_weight', models.IntegerField(default=30)),
                ('technical_knowledge_weight', models.IntegerField(default=25)),
                ('problem_solving_weight', models.IntegerField(default=20)),
                ('enthusiasm_weight', models.IntegerField(default=10)),
                ('clarity_weight', models.IntegerField(default=10)),
                ('professionalism_weight', models.IntegerField(default=5)),
                ('minimum_qualifying_score', models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('default_duration_minutes', models.IntegerField(default=30)),
                ('auto_schedule_enabled', models.BooleanField(default=False)),
                ('send_reminders', models.BooleanField(default=True)),
                ('reminder_hours_before', models.IntegerField(default=24)),
                ('enable_recording', models.BooleanField(default=True)),
                ('enable_transcription', models.BooleanField(default=True)),
                ('enable_ai_analysis', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telephonic_settings', to='job.jobmodel')),
            ],
            options={
                'db_table': 'telephonic_round_settings',
            },
        ),
        migrations.AddIndex(
            model_name='telephonicinterview',
            index=models.Index(fields=['job', 'status'], name='telephonic__job_id_d59016_idx'),
        ),
        migrations.AddIndex(
            model_name='telephonicinterview',
            index=models.Index(fields=['application', 'status'], name='telephonic__applica_7c1845_idx'),
        ),
        migrations.AddIndex(
            model_name='telephonicinterview',
            index=models.Index(fields=['scheduled_at', 'status'], name='telephonic__schedul_d0ea44_idx'),
        ),
        migrations.AddIndex(
            model_name='telephonicinterview',
            index=models.Index(fields=['status', 'scheduled_at'], name='telephonic__status_b4f355_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['session_id'], name='call_sessio_session_546c67_idx'),
        ),
        migrations.AddIndex(
            model_name='callsession',
            index=models.Index(fields=['interview'], name='call_sessio_intervi_ec8f91_idx'),
        ),
    ]
