# Generated by Django 5.2.5 on 2026-01-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephonic_round', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='candidate_joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telephonicinterview',
            name='candidate_joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telephonicinterview',
            name='status',
            field=models.CharField(choices=[('not_scheduled', 'Not Scheduled'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('joined', 'Candidate Joined'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('failed', 'Failed')], db_index=True, default='not_scheduled', max_length=20),
        ),
    ]
