# Generated by Django 5.2.5 on 2025-11-18 05:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='company',
            name='companies_c_verific_2cd7c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='company',
            name='companies_c_recruit_91612c_idx',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['verification_status', 'created_at'], name='companies_c_verific_0d69b0_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['recruiter', 'verification_status'], name='companies_c_recruit_850901_idx'),
        ),
    ]
