# Generated by Django 5.2.5 on 2025-12-30 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_delete_resumescreeningresult'),
        ('resume_screening', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matching_skills', models.JSONField(default=list)),
                ('missing_required_skills', models.JSONField(default=list)),
                ('matched_keywords', models.JSONField(default=list)),
                ('extracted_experience_years', models.FloatField(blank=True, null=True)),
                ('experience_meets_requirement', models.BooleanField(default=False)),
                ('extracted_education', models.CharField(blank=True, max_length=200, null=True)),
                ('education_meets_requirement', models.BooleanField(default=False)),
                ('is_ats_friendly', models.BooleanField(default=True)),
                ('ats_issues', models.JSONField(default=list)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('recommendation_notes', models.TextField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('screening_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening_result', to='application.applicationmodel')),
            ],
            options={
                'db_table': 'resume_screening_results',
            },
        ),
    ]
