# Generated by Django 5.2.5 on 2025-11-12 07:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('portfolio_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('linkedin_profile', models.URLField(blank=True, max_length=500, null=True)),
                ('years_of_experience', models.CharField(blank=True, max_length=20, null=True)),
                ('availability', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_salary', models.CharField(blank=True, max_length=100, null=True)),
                ('current_company', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('qualified', 'Next round qualified'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('offered', 'Offered'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('hired', 'Hired')], default='applied', max_length=30)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('interview_date', models.DateTimeField(blank=True, null=True)),
                ('recruiter_notes', models.TextField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='job.jobmodel')),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['candidate', 'status'], name='application_candida_84e04d_idx'), models.Index(fields=['job', 'status'], name='application_job_id_606b4d_idx'), models.Index(fields=['status', 'created_at'], name='application_status_91af05_idx')],
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
