# Generated by Django 5.2.5 on 2025-11-18 05:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
        ('job', '0002_alter_jobmodel_employment_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('under_review', 'Under Review'), ('qualified', 'Next round qualified'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('offered', 'Offered'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('hired', 'Hired')], db_index=True, default='applied', max_length=30),
        ),
        migrations.AlterField(
            model_name='applicationmodel',
            name='submitted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='applicationmodel',
            index=models.Index(fields=['status', 'submitted_at'], name='application_status_4711eb_idx'),
        ),
    ]
