# Generated by Django 5.2.5 on 2025-11-20 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_applicationmodel_candidate_and_more'),
        ('candidate', '0003_alter_candidateprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='candidate.candidateprofile'),
        ),
    ]
