# Generated by Django 5.2.5 on 2025-12-30 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_applicationmodel_candidate'),
        ('candidate', '0004_remove_candidateexperience_candidate_e_candida_80ca1d_idx_and_more'),
        ('job', '0003_jobmodel_screened_application_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matching_skills', models.JSONField(default=list)),
                ('missing_required_skills', models.JSONField(default=list)),
                ('matched_keywords', models.JSONField(default=list)),
                ('extracted_experience_years', models.FloatField(blank=True, null=True)),
                ('experience_meets_requirement', models.BooleanField(default=False)),
                ('extracted_education', models.CharField(blank=True, max_length=200, null=True)),
                ('education_meets_requirement', models.BooleanField(default=False)),
                ('is_ats_friendly', models.BooleanField(default=True)),
                ('ats_issues', models.JSONField(default=list)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('recommendation_notes', models.TextField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('screening_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'resume_screening_results',
            },
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='ats_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('qualified', 'Qualified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='ats_education_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='ats_experience_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='ats_keywords_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='ats_overall_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='ats_skills_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='screening_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='applicationmodel',
            index=models.Index(fields=['job', 'screening_status'], name='application_job_id_aa9b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationmodel',
            index=models.Index(fields=['ats_decision', 'ats_overall_score'], name='application_ats_dec_f8ae77_idx'),
        ),
        migrations.AddField(
            model_name='resumescreeningresult',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening_result', to='application.applicationmodel'),
        ),
    ]
