# Generated by Django 5.2.5 on 2025-12-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_resumescreeningresult_applicationmodel_ats_decision_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumeScreeningResult',
        ),
    ]
