# Generated by Django 5.2.5 on 2025-12-31 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_delete_resumescreeningresult'),
        ('selection_process', '0004_alter_selectionprocessmodel_job_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='current_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='selection_process.selectionstagemodel'),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='current_stage_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('started', 'Started'), ('qualified', 'Qualified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ApplicationStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('qualified', 'Qualified'), ('rejected', 'Rejected')], default='started', max_length=20)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='application.applicationmodel')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection_process.selectionstagemodel')),
            ],
            options={
                'db_table': 'application_stage_history',
                'ordering': ['started_at'],
                'unique_together': {('application', 'stage')},
            },
        ),
    ]
