# Generated by Django 5.2.5 on 2026-03-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_applicationmodel_current_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstagehistory',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
