# Generated by Django 5.2.5 on 2026-01-22 07:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0007_applicationmodel_current_stage_and_more'),
        ('job', '0007_jobmodel_min_experience'),
        ('selection_process', '0004_alter_selectionprocessmodel_job_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_duration_minutes', models.IntegerField(default=45)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=100)),
                ('status', models.CharField(choices=[('not_scheduled', 'Not Scheduled'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('candidate_joined', 'Candidate Joined'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], db_index=True, default='not_scheduled', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('candidate_joined_at', models.DateTimeField(blank=True, null=True)),
                ('actual_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('scheduling_notes', models.TextField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('meeting_link', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_interview', to='application.applicationmodel')),
                ('conducted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_hr_interviews', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_interviews', to='job.jobmodel')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_interviews', to='selection_process.selectionstagemodel')),
            ],
            options={
                'db_table': 'hr_interviews',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='HRRoundSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_duration_minutes', models.IntegerField(default=45)),
                ('auto_schedule_enabled', models.BooleanField(default=False)),
                ('send_reminders', models.BooleanField(default=True)),
                ('reminder_hours_before', models.IntegerField(default=24)),
                ('enable_recording', models.BooleanField(default=True)),
                ('enable_chat', models.BooleanField(default=True)),
                ('communication_weight', models.IntegerField(default=25)),
                ('culture_fit_weight', models.IntegerField(default=20)),
                ('motivation_weight', models.IntegerField(default=15)),
                ('professionalism_weight', models.IntegerField(default=15)),
                ('problem_solving_weight', models.IntegerField(default=15)),
                ('team_collaboration_weight', models.IntegerField(default=10)),
                ('minimum_qualifying_score', models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_settings', to='job.jobmodel')),
            ],
            options={
                'db_table': 'hr_round_settings',
            },
        ),
        migrations.CreateModel(
            name='InterviewChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=100)),
                ('sender_type', models.CharField(choices=[('recruiter', 'Recruiter'), ('candidate', 'Candidate')], max_length=20)),
                ('message', models.TextField()),
                ('is_system_message', models.BooleanField(default=False)),
                ('read_by_recipient', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='hr_round.hrinterview')),
            ],
            options={
                'db_table': 'hr_interview_chat_messages',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('communication_notes', models.TextField(blank=True, null=True)),
                ('culture_fit_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('culture_fit_notes', models.TextField(blank=True, null=True)),
                ('motivation_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('motivation_notes', models.TextField(blank=True, null=True)),
                ('professionalism_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('professionalism_notes', models.TextField(blank=True, null=True)),
                ('problem_solving_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('problem_solving_notes', models.TextField(blank=True, null=True)),
                ('team_collaboration_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('team_collaboration_notes', models.TextField(blank=True, null=True)),
                ('overall_impression', models.TextField(blank=True, null=True)),
                ('strengths', models.TextField(blank=True, null=True)),
                ('areas_for_improvement', models.TextField(blank=True, null=True)),
                ('general_notes', models.TextField(blank=True, null=True)),
                ('calculated_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('recommendation', models.CharField(blank=True, choices=[('strong_yes', 'Strong Yes - Hire'), ('yes', 'Yes - Hire'), ('maybe', 'Maybe - Need Discussion'), ('no', 'No - Reject'), ('strong_no', 'Strong No - Reject')], max_length=20, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='hr_round.hrinterview')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_interview_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hr_interview_notes',
            },
        ),
        migrations.CreateModel(
            name='InterviewRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('video_key', models.CharField(blank=True, max_length=500, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('thumbnail_key', models.CharField(blank=True, max_length=500, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('video_format', models.CharField(default='webm', max_length=20)),
                ('resolution', models.CharField(blank=True, max_length=20, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending Upload'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('upload_started_at', models.DateTimeField(blank=True, null=True)),
                ('upload_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='hr_round.hrinterview')),
            ],
            options={
                'db_table': 'hr_interview_recordings',
            },
        ),
        migrations.CreateModel(
            name='InterviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('decision', models.CharField(choices=[('qualified', 'Qualified'), ('not_qualified', 'Not Qualified'), ('pending_review', 'Pending Review')], default='pending_review', max_length=20)),
                ('decision_reason', models.TextField(blank=True, null=True)),
                ('next_steps', models.TextField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_interview_decisions', to=settings.AUTH_USER_MODEL)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='hr_round.hrinterview')),
            ],
            options={
                'db_table': 'hr_interview_results',
            },
        ),
        migrations.CreateModel(
            name='MeetingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('room_id', models.CharField(db_index=True, max_length=100)),
                ('recruiter_id', models.CharField(max_length=100)),
                ('candidate_id', models.CharField(max_length=100)),
                ('recruiter_connected', models.BooleanField(default=False)),
                ('candidate_connected', models.BooleanField(default=False)),
                ('is_recording', models.BooleanField(default=False)),
                ('recording_started_at', models.DateTimeField(blank=True, null=True)),
                ('recording_stopped_at', models.DateTimeField(blank=True, null=True)),
                ('connection_quality', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('recruiter_joined_at', models.DateTimeField(blank=True, null=True)),
                ('candidate_joined_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_session', to='hr_round.hrinterview')),
            ],
            options={
                'db_table': 'hr_meeting_sessions',
            },
        ),
        migrations.AddIndex(
            model_name='hrinterview',
            index=models.Index(fields=['job', 'status'], name='hr_intervie_job_id_c48e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='hrinterview',
            index=models.Index(fields=['application', 'status'], name='hr_intervie_applica_a28d0b_idx'),
        ),
        migrations.AddIndex(
            model_name='hrinterview',
            index=models.Index(fields=['scheduled_at', 'status'], name='hr_intervie_schedul_47257b_idx'),
        ),
        migrations.AddIndex(
            model_name='hrinterview',
            index=models.Index(fields=['status', 'scheduled_at'], name='hr_intervie_status_3f5c58_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewchatmessage',
            index=models.Index(fields=['interview', 'sent_at'], name='hr_intervie_intervi_31ec97_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingsession',
            index=models.Index(fields=['session_id'], name='hr_meeting__session_dca3d7_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingsession',
            index=models.Index(fields=['room_id'], name='hr_meeting__room_id_d0f059_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingsession',
            index=models.Index(fields=['interview'], name='hr_meeting__intervi_bccd9e_idx'),
        ),
    ]
