# Generated by Django 5.2.5 on 2026-02-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_round', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewchatmessage',
            name='message_type',
            field=models.CharField(default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewchatmessage',
            name='zegocloud_message_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='meetingsession',
            name='zegocloud_recording_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='meetingsession',
            name='zegocloud_recording_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='meetingsession',
            name='zegocloud_room_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='meetingsession',
            name='zegocloud_session_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
