# Generated by Django 5.2.5 on 2025-11-18 05:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateexperience',
            name='is_current',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='candidateskill',
            name='skill_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='candidateexperience',
            index=models.Index(fields=['candidate', 'is_current'], name='candidate_e_candida_80ca1d_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprofile',
            index=models.Index(fields=['location'], name='candidates_locatio_ebdbfd_idx'),
        ),
    ]
