# Generated by Django 5.2.5 on 2025-11-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_alter_candidateprofile_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='candidateexperience',
            name='candidate_e_candida_80ca1d_idx',
        ),
        migrations.RemoveField(
            model_name='candidateexperience',
            name='is_current',
        ),
        migrations.AddIndex(
            model_name='candidateexperience',
            index=models.Index(fields=['candidate'], name='candidate_e_candida_a9abb3_idx'),
        ),
    ]
