# Generated by Django 5.2.5 on 2025-11-24 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionStageModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('FileText', 'File Text'), ('Phone', 'Phone'), ('Video', 'Video'), ('Users', 'Users'), ('CheckCircle', 'Check Circle'), ('Award', 'Award'), ('Briefcase', 'Briefcase'), ('Lock', 'Lock')], default='FileText', max_length=50)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('premium_required', models.BooleanField(default=False)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('per-post', 'Per Post'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['slug'], name='selection_p_slug_ddee91_idx'), models.Index(fields=['tier', 'is_active'], name='selection_p_tier_da1d98_idx'), models.Index(fields=['order'], name='selection_p_order_ad38f7_idx'), models.Index(fields=['is_active'], name='selection_p_is_acti_960d6b_idx')],
            },
        ),
    ]
