# Generated by Django 5.2.5 on 2025-11-25 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection_process', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectionstagemodel',
            name='premium_required',
        ),
        migrations.AddField(
            model_name='selectionstagemodel',
            name='requires_premium',
            field=models.BooleanField(default=False),
        ),
    ]
