# Generated by Django 5.2.5 on 2025-11-26 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_jobmodel_employment_type_and_more'),
        ('selection_process', '0002_remove_selectionstagemodel_premium_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectionProcessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_process', to='job.jobmodel')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection_process.selectionstagemodel')),
            ],
            options={
                'db_table': 'job_selection_process',
                'ordering': ['order'],
                'unique_together': {('job', 'stage')},
            },
        ),
    ]
