# Generated by Django 5.2.5 on 2025-11-26 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_jobmodel_employment_type_and_more'),
        ('selection_process', '0003_selectionprocessmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectionprocessmodel',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_stages', to='job.jobmodel'),
        ),
        migrations.AlterField(
            model_name='selectionprocessmodel',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_processes', to='selection_process.selectionstagemodel'),
        ),
        migrations.AddIndex(
            model_name='selectionprocessmodel',
            index=models.Index(fields=['job', 'is_active'], name='job_selecti_job_id_9a1786_idx'),
        ),
        migrations.AddIndex(
            model_name='selectionprocessmodel',
            index=models.Index(fields=['job', 'order'], name='job_selecti_job_id_487ea6_idx'),
        ),
    ]
