# Generated by Django 5.2.5 on 2026-03-04 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0007_applicationmodel_current_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLetterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=250)),
                ('offered_salary', models.CharField(max_length=100)),
                ('joining_date', models.DateField()),
                ('offer_expiry_date', models.DateField()),
                ('custom_message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined')], db_index=True, default='sent', max_length=250)),
                ('candidate_response_note', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer_letter', to='application.applicationmodel')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offer_letters',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['status', 'sent_at'], name='offer_lette_status_ee7d53_idx')],
            },
        ),
    ]
