# Generated by Django 5.2.5 on 2026-03-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlettermodel',
            name='offer_letter_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
