# Generated by Django 5.2.5 on 2025-12-18 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('period', models.CharField(choices=[('month', 'Monthly'), ('3 months', '3 Months'), ('6 months', '6 Months'), ('year', 'Yearly'), ('per post', 'Per Post')], default='month', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(default=list)),
                ('button_text', models.CharField(max_length=50)),
                ('card_color', models.CharField(choices=[('cyan', 'Cyan'), ('emerald', 'Emerald'), ('gray', 'Gray')], default='cyan', max_length=20)),
                ('user_type', models.CharField(choices=[('recruiter', 'Recruiter'), ('candidate', 'Candidate')], max_length=20)),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscripton_plans',
                'ordering': ['price', 'created_at'],
                'indexes': [models.Index(fields=['user_type', 'is_active'], name='subscripton_user_ty_a3b500_idx'), models.Index(fields=['is_default'], name='subscripton_is_defa_813167_idx')],
            },
        ),
    ]
