# Generated by Django 5.2.5 on 2025-12-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplanmodel',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
