# Generated by Django 5.2.5 on 2026-04-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplanmodel',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Stripe Price ID (e.g. price_1ABC...). Leave empty for free plans.', max_length=100, null=True),
        ),
    ]
