from django.urls import path
from hr_round.views import(
    GetHRRoundSettingsAPIView,
    GetHRInterviewsAPIView,
    UppdateHRRoundSettingsAPIView,
    GetHRInterviewsAPIView,
    GetInterviewByApplicationAPIView,
    GetInterviewDetailsAPIView,
    GetUpcomingInterviewsAPIView,
    ScheduleHRInterviewAPIView,
    BulkScheduleHRInterviewsAPIView,
    RescheduleHRInterviewAPIView,
    CancelHRInterviewAPIView,
    UpdateInterviewStatusAPIView,
    StartMeetingAPIView,
    JoinMeetingAPIView,
    EndMeetingAPIView,
    # StartRecordingAPIView,
    # StopRecordingAPIView,
    GetRecordingAPIView,
    # UploadRecordingAPIView,
    DeleteRecordingAPIView,
    GetNotesAPIView,
    CreateNotesAPIView,
    UpdateNotesAPIView,
    FinalizeNotesAPIView,
    GetResultAPIView,
    FinalizeResultAPIView,
    MoveToNextStageAPIView,
    ZegoCloudWebhookAPIView,
    LeaveMeetingAPIView,
    ResetInterviewSessionAPIView

)
urlpatterns = [
    path('settings/<int:job_id>/',GetHRRoundSettingsAPIView.as_view(),name='hr-round-settings'),
    path('settings/<int:job_id>/update/',UppdateHRRoundSettingsAPIView.as_view(),name='update-hr-round'),
    path('interviews/job/<int:job_id>/',GetHRInterviewsAPIView.as_view(), name='get-interviews'),
    path('interviews/application/<int:application_id>/',GetInterviewByApplicationAPIView.as_view(),name='hr-interview-by-application'),
    path('interview/<int:interview_id>/',GetInterviewDetailsAPIView.as_view(),name='hr-interview-details'),
    path('interviews/upcoming/',GetUpcomingInterviewsAPIView.as_view(),name='upcoming-interview'),
    path('interview/schedule/',ScheduleHRInterviewAPIView.as_view(),name='shcedule-interview'),
    path('interview/bulk-schedule',BulkScheduleHRInterviewsAPIView.as_view(),name='bulk-schedule-interview'),
    path('interview/<int:interview_id>/reschedule/',RescheduleHRInterviewAPIView.as_view(),name='interview-reschedule'),
    path('interview/<int:interview_id>/cancel/',CancelHRInterviewAPIView.as_view(),name='cancel-interview'),
    path('interview/<int:interview_id>/udpate/status/',UpdateInterviewStatusAPIView.as_view(),name='update-interview-status'),
    path('meeting/start/',StartMeetingAPIView.as_view(),name='start-meeting'),
    path('meeting/join/',JoinMeetingAPIView.as_view(),name='join-meeting'),
    path('meeting/end/',EndMeetingAPIView.as_view(),name='end-meeting'),
    path('meeting/leave/', LeaveMeetingAPIView.as_view(), name='leave-meeting'),
    path('meeting/reset/', ResetInterviewSessionAPIView.as_view(), name='reset-meeting'),
    # path('interview/start-recording/',StartRecordingAPIView.as_view(),name='start-recording'),
    # path('interview/stop-recording/',StopRecordingAPIView.as_view(),name='stop-recording'),
    path('interview/<int:interview_id>/recordings/',GetRecordingAPIView.as_view(),name='get-recordings'),
    # path('interview/recording/upload/',UploadRecordingAPIView.as_view(),name='upload-recording'),
    path('interview/<int:interview_id>/delete/recording/',DeleteRecordingAPIView.as_view(),name='delete-recording'),
    path('interview/<int:interview_id>/notes/',GetNotesAPIView.as_view(),name='get-interview-notes'),
    path('interview/create-note/',CreateNotesAPIView.as_view(),name='create-note'),
    path('interview/<int:interview_id>/update-note/',UpdateNotesAPIView.as_view(),name='update-note'),
    path('interview/<int:interview_id>/finalize-note/',FinalizeNotesAPIView.as_view(),name='finalize-note'),
    path('interview/<int:interview_id>/results/',GetResultAPIView.as_view(),name='interview-results'),
    path('interview/results/finalize/',FinalizeResultAPIView.as_view(),name='finalize-results'),
    path('interview/move-to-next-stage/',MoveToNextStageAPIView.as_view(),name='move-to-next-stage'),
    # path('inteview/<int:interview_id>/stats/',GetHRInterviewStatsAPIView.as_view(),name='get-interview-stats'),
    path('webhooks/zegocloud/',ZegoCloudWebhookAPIView.as_view(), name='zegocloud-webhook'),
    
]