from django.urls import path
from . views import(CsrfCookieView,
                    RegisterView, 
                    LoginView, 
                    RefreshView, 
                    LogoutView, 
                    RegisterOtpView,
                    RequestOtpView,
                    ResendOtpView, 
                    VerifyOtpView, 
                    ForgotPasswordView,
                    ResetPasswordView,
                    FetchUserView,
                    GoogleAuthView,
                    GithubAuthView,
                    CloudinarySignatureApiView,
                    UpdateUserProfileView,
                    debug_cookies,
                    LinkedInAuthView,
                    CookieTokenRefreshView)
urlpatterns = [
    path('me/', FetchUserView.as_view(), name='auth_me'),
    path('csrf-cookie/',CsrfCookieView.as_view(),name='csrf-cookie'),
    path('token/refresh/',CookieTokenRefreshView.as_view(),name='token-refresh'),
    path('register/',RegisterView.as_view(),name='register'),
    path('register-otp/',RegisterOtpView.as_view(), name='register-otp'),
    path('request-otp/',RequestOtpView.as_view(),name='request-otp'),
    path('resend-otp/',ResendOtpView.as_view(),name='resend-otp'),
    path('verify-otp/',VerifyOtpView.as_view(),name='verify-otp'),
    path('forgot-password/',ForgotPasswordView.as_view(),name='forgot-password'),
    path('reset-password/',ResetPasswordView.as_view(),name="reset-password"),
    path('login/',LoginView.as_view(),name='login'),
    path('fetch-user/',FetchUserView.as_view(),name='fetch-user'),
    path('token/refresh/',RefreshView.as_view(),name='refresh'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('google/', GoogleAuthView.as_view(), name='social_google'),
    path('github/',GithubAuthView.as_view(), name='social_google'),
    path('linkedin/',LinkedInAuthView.as_view(), name="social_linkedin"),
    path('cloudinary/get-signature/', CloudinarySignatureApiView.as_view(), name='cloudinary-signature'),
    path("user/update-profile/", UpdateUserProfileView.as_view(), name="update-profile"),
    path('debug-cookies/', debug_cookies, name='debug-cookies'),

]
 