# Generated by Django 5.2.5 on 2025-10-27 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('work_type', models.CharField(choices=[('hybrid', 'Hybrid'), ('remote', 'Remote'), ('onsite', 'Onsite')], max_length=20)),
                ('employment_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=20)),
                ('compensation_range', models.CharField(blank=True, max_length=100, null=True)),
                ('posting_date', models.DateField(auto_now_add=True)),
                ('cover_image', models.URLField(blank=True, max_length=500, null=True)),
                ('role_summary', models.TextField(blank=True, null=True)),
                ('skills_required', models.JSONField(blank=True, default=list)),
                ('key_responsibilities', models.TextField(blank=True, null=True)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('application_link', models.URLField(blank=True, max_length=500, null=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('applicants_visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed'), ('draft', 'Draft')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recruiter', 'status'], name='jobs_recruit_ff4641_idx'), models.Index(fields=['company', 'status'], name='jobs_company_0582d9_idx'), models.Index(fields=['status', 'posting_date'], name='jobs_status_2c2d9e_idx')],
            },
        ),
    ]
