# Generated by Django 5.2.5 on 2025-11-18 05:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_remove_company_companies_c_verific_2cd7c4_idx_and_more'),
        ('job', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='employment_type',
            field=models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='job_title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='location',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed'), ('draft', 'Draft')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='work_type',
            field=models.CharField(choices=[('hybrid', 'Hybrid'), ('remote', 'Remote'), ('onsite', 'Onsite')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='jobmodel',
            index=models.Index(fields=['location', 'status'], name='jobs_locatio_95079b_idx'),
        ),
    ]
