# Generated by Django 5.2.5 on 2025-12-30 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_jobmodel_employment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='screened_application_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='screenig_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='screening_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='screening_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('paused', 'Paused')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='total_application_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ATSConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills_weight', models.IntegerField(default=40)),
                ('experience_weight', models.IntegerField(default=30)),
                ('education_weight', models.IntegerField(default=20)),
                ('keywords_weight', models.IntegerField(default=10)),
                ('passing_score', models.IntegerField(default=60)),
                ('required_skills', models.JSONField(default=list)),
                ('preferred_skills', models.JSONField(default=list)),
                ('minimum_experience_years', models.IntegerField(default=0)),
                ('required_education', models.CharField(blank=True, max_length=100, null=True)),
                ('important_keywords', models.JSONField(default=list)),
                ('auto_rejection_missing_skills', models.BooleanField(default=False)),
                ('auto_reject_below_experience', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ats_config', to='job.jobmodel')),
            ],
            options={
                'db_table': 'ats_configurations',
            },
        ),
    ]
