# Generated by Django 5.2.5 on 2025-12-30 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_jobmodel_screened_application_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ATSConfiguration',
        ),
    ]
