# Generated by Django 5.2.5 on 2026-01-02 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_delete_atsconfiguration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='screened_application_count',
            new_name='screened_applications_count',
        ),
        migrations.RenameField(
            model_name='jobmodel',
            old_name='total_application_count',
            new_name='total_applications_count',
        ),
    ]
