# Generated by Django 5.2.5 on 2026-01-02 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_rename_screened_application_count_jobmodel_screened_applications_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='screenig_started_at',
            new_name='screening_started_at',
        ),
    ]
