# Generated by Django 5.2.5 on 2026-01-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_rename_screenig_started_at_jobmodel_screening_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='min_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
